#ifndef DEFINES_H
#define DEFINES_H

#define VIDEO_TEXT_MODE_MEMORY_ADDR (0xB8000);
#define VGA_WIDTH 80
#define VGA_HEIGHT 20
#define TOTAL_INTERRUPTS 256
#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#endif